[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kawa"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.14.6",
    "ty>=0.0.1a28",
    "pytest>=9.0.1",
]
